
FROM node:18 as builder

WORKDIR /node-app

COPY package*.json ./

RUN npm install

COPY . .


FROM node:alpine

WORKDIR /node-app

COPY --from=builder /node-app/. ./

EXPOSE 3000

CMD ["npm", "start"]
